### ISSUE TITLE
Bug fix click person name not working

### ISSUE THREAD

**Issue by JasonLo** [UW-Madison-DSI/faculty-search#93]
Clicking a person in the search result is do nothing?
It should show the publication records on our back-end.

**Comment by amegahed** [comment]
The results that are returned from the author search API route do not include any publication information.  Should I be calling the API differently to also get the publication information or should I make an additional call to the author search API route with the person's name in order to get the publication info?

**Comment by JasonLo** [comment]
For some reason, it only works in DEV? @amegahed
